### ISSUE TITLE
[BUG] Unit tests on future/v0.3.0 do not compile — exec_* called with 3 args, pars_dispatch with 4 (signatures take 2/3)

### ISSUE THREAD

**Issue by seesee010** [lo3-lang/lo3#133]
﻿## Summary

On `future/v0.3.0`, `test/unit/test_execute.c` and `test/unit/test_parsing.c` call the exec functions with an extra argument that does not exist in any header or implementation:

```c
// test_execute.c
static char dummy[2] = {0, 0};
exec_cmp(nval(5), nval(5), dummy);          // exec_cmp takes 2 args

// test_parsing.c
char arr[2] = {0};
int r = pars_dispatch(RET_good, dummy, dummy, arr);   // pars_dispatch takes 3 args
```

`src/internal/specific-language.h` declares `void exec_cmp(lo3_val a1, lo3_val a2);` and `int pars_dispatch(lo3_cmds cmd, lo3_val a1, lo3_val a2);` ? on **both** branches. So the whole Unity test suite fails to compile on `future/v0.3.0` (`error: too many arguments to function`). On `main` the test files still use the correct 2/3-arg calls, so this is a regression introduced on the feature branch.

Combined with #114/#118 (main build broken) this means **nothing on future/v0.3.0 currently compiles**: not the interpreter, not the tests.

## Affected code

- `test/unit/test_execute.c` ? every `exec_cmp` / `exec_small` / `exec_big` / `exec_label` call (lines 50?147)
- `test/unit/test_parsing.c` ? `pars_dispatch` calls (lines 161?184)

## Suggested fix

Either revert the test files to the 2/3-argument calls (as on `main`), or ? if a new parameter is actually planned ? add it to the declarations and implementations first. Tests and implementation must change in the same commit.

Affects: `future/v0.3.0` only.

---
?? This issue was created by Claude (automated bug hunt).

---
**Parent Issue**: #213 - Test Suite Issues Overview

**Comment by seesee010** [comment]
**Parent Issue**: Part of #213 - Test Suite Issues Overview

**Comment by seesee010** [comment]
**[RELATIONSHIP]** This is a child of #213 - Test Suite Issues Overview
